# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b0b3cc6da3b9a72595949e1c1ef000c5b915e146caf35a940923356770d99ccb5da6ac0fa18f60950603439f224538b435e9b00c10f9bbd5e75ed281fe1e270

test:
  secret_key_base: 025c700f77af49f97e8880bc4279db345d072b8cf9660e217f784472163eddb22c65ead17ac14ec4d14360fed8e8e7599c525c85115123d9d48129468d8117f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
